export const STUDENTS = [
  {
    id: "0",
    name: "Aranka",
    age: "25",
    email: "aranka@wincacademy.nl",
    phoneNumber: "+316640027141",
    imgUrl: "/studentImages/0.jpg",
  },
  {
    id: "1",
    name: "Evelyn",
    age: "30",
    email: "evelyn@wincacademy.nl",
    phoneNumber: "+316640029041",
    imgUrl: "/studentImages/1.jpg",
  },
  {
    id: "2",
    name: "Floris",
    age: "50",
    email: "floris@wincacademy.nl",
    phoneNumber: "+316690027141",
    imgUrl: "/studentImages/2.jpg",
  },
  {
    id: "3",
    name: "Hector",
    age: "27",
    email: "hector@wincacademy.nl",
    phoneNumber: "+314540027141",
    imgUrl: "/studentImages/3.jpg",
  },
  {
    id: "4",
    name: "Martina",
    age: "44",
    email: "martina@wincacademy.nl",
    phoneNumber: "+316623027141",
    imgUrl: "/studentImages/4.jpg",
  },
  {
    id: "5",
    name: "Maurits",
    age: "45",
    email: "maurits@wincacademy.nl",
    phoneNumber: "+316640237141",
    imgUrl: "/studentImages/6.jpg",
  },
  {
    id: "6",
    name: "Rahima",
    age: "22",
    email: "rahima@wincacademy.nl",
    phoneNumber: "+316667027141",
    imgUrl: "/studentImages/6.jpg",
  },
  {
    id: "7",
    name: "Sandra",
    age: "39",
    email: "sandra@wincacademy.nl",
    phoneNumber: "+316880027141",
    imgUrl: "/studentImages/7.jpg",
  },
  {
    id: "8",
    name: "Storm",
    age: "33",
    email: "storm@wincacademy.nl",
    phoneNumber: "+316890027141",
    imgUrl: "/studentImages/8.jpg",
  },
  {
    id: "9",
    name: "Wietske",
    age: "37",
    email: "wietske@wincacademy.nl",
    phoneNumber: "+316640337141",
    imgUrl: "/studentImages/9.jpg",
  },
];
